
network=$1

EXTEND_ESLINT="EXTEND_ESLINT=true"
GENERATE_SOURCEMAP="GENERATE_SOURCEMAP=true"

REACT_LOCAL_ENV='REACT_ENV="development"'
REACT_LOCAL_APP_ENV='REACT_APP_ENV="development"'
REACT_LOCAL_APP_NETWORK='REACT_APP_IC_NETWORK="local"'

EXTEND_IC_ESLINT="EXTEND_ESLINT=true"
GENERATE_IC_SOURCEMAP="GENERATE_SOURCEMAP=false"
REACT_IC_ENV='REACT_ENV="production"'
REACT_IC_APP_ENV='REACT_APP_ENV="production"'
REACT_IC_APP_NETWORK='REACT_APP_IC_NETWORK="ic"'

local_env="${GENERATE_SOURCEMAP}\n${EXTEND_ESLINT}\n${REACT_LOCAL_ENV}\n${REACT_LOCAL_APP_ENV}\n${REACT_LOCAL_APP_NETWORK}\n"
ic_env="${GENERATE_IC_SOURCEMAP}\n${EXTEND_IC_ESLINT}\n${REACT_IC_ENV}\n${REACT_IC_APP_ENV}\n${REACT_IC_APP_NETWORK}\n"

if [ $network = "ic" ]
then
  printf $ic_env > .env
else
  printf $local_env > .env
fi
